### ISSUE TITLE
cannot Initialize Disasm

### ISSUE THREAD

**Issue by ARM830** [crypto2011/IDR#52]
i dont know what is it。
what need i to do?
sorry for this，  i noob

**Comment by crypto2011** [comment]
Check file dis.dll in IDR home directory

**Comment by kazkansouh** [comment]
Hello,

I just came across this project and it looks nice and is easy to use.

However, I got the same error (as well as in #47 ). Process followed was downloading the exe from the release page and tried running it. Expected behaviour was to work.

> Check file dis.dll in IDR home directory

Can I suggest updating the readme on the main page to indicate that in the case of this error message the dis.dll should be downloaded from the repo (I ended up installing Borland C++ 6 to compile it before realising this)!

**Comment by crypto2011** [comment]
Ok, done.

**Comment by ARM830** [comment]
thank for your  help
but i only download idr.exe
what need i to do?
